### ISSUE TITLE
Timeout to Close Classifier

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#28]
There should be a timeout to close the classifier after a certain amount of inactivity. Before closing, a model should pop up asking the user if they are still present.

**Comment by beckyrother** [comment]
InVision: https://invis.io/WFNHU46KV6J#/336156649_2-8_Still_There-

Copy needs some help. Currently: 
Still debating?
Tap “Still working” before the countdown runs out or this workspace will be closed.

**Comment by wgranger** [comment]
I'm going to set this to five minutes for now. We can always change this in the future if needed.

**Comment by wgranger** [comment]
Are you opposed to "Still There?" instead of "Still debating?" 

I think "Still there" is a bit more to the point and simple as opposed to "Still debating."

**Comment by beckyrother** [comment]
"Still there" is fine! I used "still debating" in the hopes that they were afk because they were talking to other people, but agreed, "still there" makes more sense.
