### ISSUE TITLE
Leveling Max Out

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#29]
Although it would be rare for a user to reach the max level (level five, 25 classifications) this will inevitably happen, and there should be some sort of max out state. We also discussed the possibility of something exciting happening whenever a user advances levels.

**Comment by wgranger** [comment]
Along with the leveler, we also discussed having an animation, or something interesting, when a user reaches a new level.

**Comment by wgranger** [comment]
@beckyrother Based on our Slack convo, I'm going to set a max out level as "Master" with the message "You're a Pro" instead of "Classify X more Galaxies to level up." Do we also want the level to go higher than five?

**Comment by beckyrother** [comment]
I love that! Let's keep it at 5 for now and revisit in a few months if we hear any comments about it 👍
