### ISSUE TITLE
Animate tile advance

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#57]
When moving to a new cutout tile, the centerpiece should advance by fading out current galaxies, zooming out, moving to the next tile, and zooming back in while fading in new galaxies.

Currently, the tile simply flicks to the next image.

**Comment by wgranger** [comment]
@beckyrother I believe you have a link to how this should look?

**Comment by beckyrother** [comment]
@wgranger yes! https://tympanus.net/Development/PageTransitions/ – the last one, Slide
