### ISSUE TITLE
Different messages when classifying

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#58]
Currently, a user will always see "you just science'd" after making a classification. We discussed showing a variety of different messages to surprise users and have them continue classifying.

**Comment by wgranger** [comment]
@beckyrother This is worth thinking about over the next week or so.

**Comment by beckyrother** [comment]
I'm going to post this in Slack, would love to hear everyone's ideas for this

**Comment by beckyrother** [comment]
"Thanks for your help!"
"You're a real scientist!"
"Don't stop now!"
"Did you know you can do this at home on zooniverse.org"
