### ISSUE TITLE
What happens when the user gets to the next level?

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/galaxy-zoo-touch-table#69]
Couple of ideas:

– a pulse of the user's color emits from the workspace out into the middle?
– a lil bit of confetti comes out? 
![level-up-confetti](https://user-images.githubusercontent.com/1392130/59633894-230d6f80-9113-11e9-8473-c1d96462e4ca.gif)

Thoughts?

**Comment by wgranger** [comment]
I could look into animating this. I think the first (color emitting) would be easier to accomplish than the confetti. This is def a stretch goal until I get some of the main functionality polished up.

**Comment by beckyrother** [comment]
Sounds good, definitely low priority. I can look around for a codepen if that's useful at all, otherwise i can try to make an animation
