### ISSUE TITLE
What Happens When Subjects Retire?

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#77]
The retirement rate is currently at 25. However, a subject can be classified more than 25 times, but this will look awkward with the current UI (eg. 27/25 classifications?).

What should we do when a subject gets to 25 classifications (retires)? Still allow users to interact with the galaxies but disable classification? Dim out and disable to galaxies?

**Comment by beckyrother** [comment]
Two options: 
1. Grey it out and disable it

2, Allow a user to drag it into the workspace and then show them this modal:
![image](https://user-images.githubusercontent.com/1392130/60998775-34ffbe00-a31f-11e9-92d0-6c0a5adabc3a.png)

**Comment by wgranger** [comment]
Sounds good. I think I can implement this pretty quickly.

**Comment by beckyrother** [comment]
Thank you!

**Comment by wgranger** [comment]
@beckyrother Did we decide there will be a visual indicator somewhere on the galaxy in the center if it is retired?

**Comment by beckyrother** [comment]
Yes, please keep it green/editable but dim it to 20% or whatever percentage you're using elsewhere
