### ISSUE TITLE
Occasionally Move Map

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#78]
I can see a situation on the table where users will not spot the "move map" button and be stuck on a single location for a while. This could be a problem if all galaxies on that spot get classified and users don't know they should move the map. 

Because of this, there needs to be a check frequently that there are still galaxies to be classified at the current table location.

**Comment by beckyrother** [comment]
Should those move map buttons pulse a little also, like the galaxy highlights?

**Comment by wgranger** [comment]
Yes, I think they need to be more noticeable.
