### ISSUE TITLE
Touchtable Observations: July 2019

### ISSUE THREAD

**Issue by wgranger** [zooniverse/galaxy-zoo-touch-table#94]
Few items I noticed in recently observing the touch table:
- [ ] Timeouts should be shorter. Currently, the modal appears at 2:30. Perhaps it should be reduced by a minute?
- [ ] Moving the map should not cancel out all galaxies that are being dragged
- [ ] Some users might not be familiar with the terminology "drag and drop"

**Comment by beckyrother** [comment]
Timeouts: Yes, shorter is good

- [ ] When users are already at the table and a new user opens a workstation, it's not clear to the new person where they should drag from (similar to the last point ☝️) Is there some way to maybe wiggle the galaxies after every new workstation opens?

**Comment by wgranger** [comment]
Yes. There is a PR up to wiggle the galaxies after ten seconds of inactivity. I'll see if I can make a change to also wiggle the galaxies when a new user joins.
